package banco;

// BUSQUEDA LINEAL
public class GestorCuentas {

    public static CuentaBancaria buscarCuentaLineal(CuentaBancaria[] cuentas, String numero) {
/**                                                    ARREGLO DONDE BUSCARA 
ESTE METODO LO QUE HACE ES APLICAR LA BUSQUEDA LINEAL SONBRE CUENTA BANCARIA
LO QUE HACE ES  LA BUSQUEDA LINEAL SOBRE UN ARREGLO DE CUENTAS.  
ESTE METODO SE PUEDE METER EN CUENTA BANCARIA JEJEJE
**/
        for (int i = 0; i < cuentas.length; i++) { 
            if (cuentas[i] != null && //AQUI TENEMOS EL CASO BASE, LA POSICION TIENE UNA CUENTA?
                cuentas[i].getNumeroCuenta().equals(numero)) { //AQUI COMPARA USAMOS EQUALS PQ ES UN STRING Y ASI SE USA EN JAVA 
                return cuentas[i]; // AL BUSCAR DE CUENTA EN CUENTA, LO HACE UNA BUSQUEDA LINEAL 
            }
        }

        return null;// REVISO TODO EL ARREGLO Y NO ENCONTRO NADA.
    }
}

/**
 PERO Y CUENTA CORRIENTE?
AQUI USAMOS LA CUENTA BANCARIA  POR POLIMOSFIMO, YA QUE CUENTA CORRIENTE Y CUENTA AHORRO HEREDAN
DE CUENTA BANCARIA , POR LO TANTO EL ARREGLO PUEDE GUARDAR DE AMBOS TIPOS.

Y PQ CREAR OTRA CLASE?
BUENO YO APLIQUE OTRA CLASE PQ AL SER POLIMORFISMO PODEMOS BUSCAR DE UNA LISTA DE CUENTAS Y NO QUE ENTRE CUENTAS SE 
BUSQUE,   TAMBIEN PQ AL SER UNA BUSQUEDA LINEAL, ESTE BUSCA EN UN CONJUNTO. CONJUNTO QUE TIENE CUENTA BANCARIA. 
**/
